# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-29 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0006_auto_20180829_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_name',
        ),
    ]
