# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0007_auto_20180829_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='college',
            field=models.CharField(blank=True, default='Enter Your College Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='job',
            field=models.CharField(blank=True, default='Enter Your job place', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='position',
            field=models.CharField(blank=True, default='Enter Your Work position', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='school',
            field=models.CharField(blank=True, default='Enter Your Schooling', max_length=200, null=True),
        ),
    ]
